### ISSUE TITLE
[Feature Request] Store report files for each build separately

### ISSUE THREAD

**Issue by molsky** [jenkinsci/zaproxy-plugin#10]
Currently all report files are stored only to job's workspace and every time when the job is build the files are overwritten if they have same name. For example Robot Framework plugin stores all specific files separately to each build so you can easily find old log and reports files from specific job build number.

![build_page](https://cloud.githubusercontent.com/assets/1943521/10732417/9af2df5a-7c02-11e5-9a6b-9873f39377f0.png)

**Comment by thilina27** [comment]
adding build number to the end of the report will be good?

**Comment by johannol** [comment]
Hi,

I'm not sure this is a good pattern:
1) If i well understood, this is already possible to archive repports using
the Jenkin's "archive artefacts" checkbox at the end of the Job config
2) This will break other work in progres, like a sonarqube plugin, which is
taking zaproxy report and inject results into Sonar [which is the right
tools to show issues/history].

My 2 cents

2015-10-26 16:14 GMT+01:00 Thilina Madhusanka <notifications@github.com>:

**Comment by thilina27** [comment]
Adding build number to the end of the report if it is requested, like putting a check box to select it or not. 

Will it break the other work?

**Comment by molsky** [comment]
This is more.like "nice to have" request. We will go with "archive artefacts" plugin. I haven't tested this yet but does ZAProxy plugin's report filename field support Jenkins environment variables in it?

**Comment by thilina27** [comment]
I dont think its support jenkins environment veriable to use in its file name. haven't tested it. Ill give it a try.

**Comment by thilina27** [comment]
It dosent support it. but plugin can be change to add the build number in to the file name if user need. i dont think it will be a bad idea.

**Comment by davehunt** [comment]
+1 for expanding environment variables in string inputs.

**Comment by thilina27** [comment]
Added simple way to append build number to the report file [1]
![image](https://cloud.githubusercontent.com/assets/13943331/10812374/7671078e-7e3b-11e5-8ad7-facbd9fce6bb.png)

[1] - https://github.com/thilina27/zaproxy-plugin/tree/buildnumber 

Is this ok?

**Comment by davehunt** [comment]
Why not just allow environment variable expansion, then your report name can be `report-${BUILD_NUMBER}`. This allows for ultimate flexibility and no need for additional checkboxes.

**Comment by thilina27** [comment]
This is a modification i have been using for some time now in my local builder. i don't know if there is a way to get the Jenkins env. variable via string inputs.  If not string have to be checked and then get the variable according to input of the user.

**Comment by davehunt** [comment]
Here's an example of a plugin expanding variables from string inputs: https://github.com/mozilla/testdroid-marionette-plugin/blob/318dfc70fd8519f8fc5a187431049ab58974471b/src/main/java/jenkins/plugins/testdroid/DeviceSessionWrapper.java#L424-L443

**Comment by thilina27** [comment]
This feature is now available 

https://github.com/jenkinsci/zaproxy-plugin/commit/c0d47ee017834fdc3cdf0544cf88d5eb31868efb
