### ISSUE TITLE
Login with Active script 

### ISSUE THREAD

**Issue by tzvetkov75** [jenkinsci/zaproxy-plugin#11]
PostLogin Form is not very suitable for real applications. Most of the application user CSRF token or even require multiple factors. Please add login with authentication script that is recored in advance.
Thanks

**Comment by thilina27** [comment]
Im not much familiar with this. 
If you can add some reference from OWASP ZAP tool, it ll be helpful.
Im bit busy but ill check it when i got time.  
If you can post some reference from it will be helpful to me.

**Comment by tzvetkov75** [comment]
There are two points
1) load authentication script (if it is not already manually configured) with 
       _zapClientAPI.script.load(String name, String type, String engine, String file, String descr)_

2) set the loaded script as authentication method (alternative to FormBased) 
   _zapClientAPI.authentication.setAuthenticationMethod_   with _scriptBasedAuthentication_ pointing to the loaded script with some params URL, Request type (POST,GET)

You  will be great if you can add this options

**Comment by thilina27** [comment]
Thanks ill look in to it as soon as i get time. 
You can edit the plugin code and make a PR if its possible to you.

**Comment by seanleblanc** [comment]
Is it possible to do vanilla login and launch an attack via this plugin?

**Comment by tzvetkov75** [comment]
if consider under "vanillia login" separate independent login to the ZAP plugin. Yes it is possible if cookie is used for session management
- add the  cookie name to ZAP http session params (if not already listed)
- make login with you application (like selenium app, manually etc) through ZAP proxy 
- set the right active http  session in ZAP (if not recognised automatically)
- start the ZAP plugins
 
I have no real environment to make the change PR, test it. Really have not idea of jenkins plugins structure. I will try it, but will take some time
