### ISSUE TITLE
org.zaproxy.clientapi.core.ClientApiException: Invalid or missing API key

### ISSUE THREAD

**Issue by yuri1969** [jenkinsci/zaproxy-plugin#13]
Using ZAP_2.4.2 with default configuration and ZAProxy 1.1.8. 

Any simple flow ends with the exception mentioned in the title. I can see the ZAP is being started with -config api.key=ZAPROXY-PLUGIN. However, I can't change/set the key value. 

The OWASP ZAP documentation mentions a way to disable the key via api.disablekey = true but this doesn't work either.

Editing ZAP's xml/config.xml doesn't seem to work either.

**Comment by thilina27** [comment]
Can you attache a Jenkins log ? This error never occurred to me after the version 1.1.7.

**Comment by yuri1969** [comment]
There is a complete stdout from the ZAP job: http://pastie.org/private/jqiinnzmjj3v1z72nxosrw

Jenkins log seems not to contain any ZAP job related info - I have always ran the ZAP job manually.

**Comment by thilina27** [comment]
I m not able to reproduce this error. 
can you try to reinstalling zap and zaproxy plugin.

**Comment by yuri1969** [comment]
OK, removed the plugin along with the Cusotm Tools one. Restarted Jenkins and now it works as a charm. Thanks

**Comment by thilina27** [comment]
no problem. have a good time.
