### ISSUE TITLE
Error : zapProgram is missing

### ISSUE THREAD

**Issue by laurentPereira** [jenkinsci/zaproxy-plugin#16]
Hello, 

I have this error message after installing the plugin:  java.lang.IllegalArgumentException: zapProgram is missing.

ZAPProxy is running with the option -daemon on the server:
[/home/ZAP_2.4.3] ./zap.sh -host localhost -port 8050 -daemon

Logs: ZAP is now listening on localhost: 8050

# My Jenkins configuration : 

![capture](https://cloud.githubusercontent.com/assets/16546038/12098617/9541857c-b323-11e5-9647-ae4a07d01794.PNG)

![capture1](https://cloud.githubusercontent.com/assets/16546038/12098424/8baa95e0-b322-11e5-8b03-6ded964ed5f3.PNG)

Do you have a solution  ?

# My configuration : 
ZAP 2.4.3
ZAP-Plugin : 1.1.9

# FYI : 
I have the same result with the plugin "Install custom tools"

Thanks

**Comment by thilina27** [comment]
This plugin will automatically start up the zap application , you dont need to start it manually. 

If can you see if your custom tool  configuration are correct ? 
can you see if the zap application downloaded and installed in your custom tool installation location ? 

If you use ZAP already installed the you need to set ZAPROXY_HOME="/home/thilinam/ZAP" like this in your /etc/environment and give the ZAPROXY_HOME as the field value

**Comment by laurentPereira** [comment]
ZAPROXY_HOME is configured

INFO: Test #35 main build action completed: FAILURE
autoInstall [false]
toolUsed [ZAPROXY]
zapHome [ZAPROXY_HOME]

With variable defined by Jenkins Jobs (script shell) : 
[Test] $ /bin/sh -xe /tmp/hudson7292207131928826692.sh
+ ZAPROXY_HOME=/home/ZAP
+ export ZAPROXY_HOME
+ echo $ZAPROXY_HOME
/home/ZAP
Perform ZAProxy
ERROR: java.lang.IllegalArgumentException: zapProgram is missing

Or by /etc/environnement
tail /etc/environnement
ZAPROXY_HOME="/home/ZAP"
$ZAPROXY_HOME/zap.sh -h

Found Java version 1.7.0_79
Available memory: 64454 MB
Setting jvm heap size: -Xmx512m

Any idea why the function "retrieveZapHomeWithToolInstall" return a null result ?

Thx
...

**Comment by laurentPereira** [comment]
OK, I found !

I need to use EnvInject Plugin in jobs to defined ZAPROXY_HOME in Jenkins

[EnvInject] - Variables injected successfully.
Perform ZAProxy
zapProgram = /home/ZAP

Thx

**Comment by thilina27** [comment]
Grt :+1: 

Btw what i did was 
set ZAPROXY_HOME= "/home/zap" (this dir contains the zap.sh)
Then select zaproxy already installed and inset ZAPROXY_HOME to the field. 
It works fine.
