### ISSUE TITLE
variable expansion?

### ISSUE THREAD

**Issue by strowi** [jenkinsci/zaproxy-plugin#22]
Hi,

would it be possible to make jenkins environment variables available within the plugin?
E.g. i would like to fill in the target-url filename/-path etc. from variables contained in the website-repository...

regards,
strowi

**Comment by thilina27** [comment]
environment variables are allowed to fill in for the report name. You want to add environment variable to the target URL ?

**Comment by meljbruno** [comment]
I'm also looking for this functionality. Right now environment variables and parameters can be expanded in the ReportName field, but not in the Target URL field or a number of other fields where this would be useful.

**Comment by whren** [comment]
Hi,

We have made PR #39 in order to address this feature.

zapProxyHost, zapProxyPort, targetURL, excludedUrl, filenameSaveSession, zapDefaultDir, cmdLinesZAP properties are candidate for replacement macro call.

**Comment by JordanGS** [comment]
Resolved in pull request #41, closing for now. Please look forward to the future release.
