### ISSUE TITLE
[Feature request] Break the build when issues are found

### ISSUE THREAD

**Issue by rares-suciu** [jenkinsci/zaproxy-plugin#23]
Hi,

Is it possible to add a feature (or if it exists, I couldn't find it) to break the build when issues are found ?
We are using Jenkins, after running the teststhe build is successful and the html report is generated, and (as expected, the vulnerabilities are left on purpose) 2 high alerts are generated for xss and sql injection vulnerabilities. In this case we would like to "break the build"
Is this currently possible ? If so, could someone please provide an example ?

Thank you so much,
Rares

**Comment by davehunt** [comment]
Duplicate of [JENKINS-30035](https://issues.jenkins-ci.org/browse/JENKINS-30035)

**Comment by JordanGS** [comment]
This issue will be closed, all future issues will be created [here](https://issues.jenkins-ci.org/browse/JENKINS-30035?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20zaproxy-plugin). The GitHub issue tracker will be closed in favor of using the Jenkins JIRA issue tracker. If you would like to reopen this issue, please do so :)
