### ISSUE TITLE
Filename for report with user environment variables

### ISSUE THREAD

**Issue by freddy3004** [jenkinsci/zaproxy-plugin#25]
Hi,

The problem is the replacement in hard of the user environment variables in the build configuration when the job build.

For example the "Filename for report" in the job's configuration is :
Before the build -> report_${BUILD_NUMBER}
After the build -> report_24

Consequently, for the next builds the filename for report will be the same (in my example : report_24)  even if the build number increase.

I am french, sorry for my english. Therefore I hope that is still clear.

**Comment by hackthem** [comment]
Hi,

It's fixed in the next release. 

Thank you.

Abdellah AZOUGARH
