### ISSUE TITLE
[Feature Request] NTLM Authentication Support

### ISSUE THREAD

**Issue by theHackPot** [jenkinsci/zaproxy-plugin#28]
Hi,
Would it be possible to add NTLM authentication support so that it can be configured via the plugin?

**Comment by JordanGS** [comment]
@theHackPot Hello, i just took over the project. what do you mean?

**Comment by theHackPot** [comment]
Hi,

The plugin supports form based and script based authentication.

I couldn't see any options/fields to set a username/password pair of
credentials used for HTTP/NTLM authentication.

**Comment by JordanGS** [comment]
@theHackPot I'll add it to the to do list but I'll have no way of testing this myself, would you be willing to test and let me know if it works?

**Comment by JordanGS** [comment]
This issue will be closed, all future issues will be created [here](https://issues.jenkins-ci.org/browse/JENKINS-30035?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20zaproxy-plugin). The GitHub issue tracker will be closed in favor of using the Jenkins JIRA issue tracker. If you would like to reopen this issue, please do some so :)
