### ISSUE TITLE
Feature: Scan & Spider Coverage Control (instead of hardcoded "false" or "" to the API call)

### ISSUE THREAD

**Issue by mabdelmoez** [jenkinsci/zaproxy-plugin#34]
Hi,

Feature: Add scan coverage control section on the jenkins plugin UI.  Where the user can control the depth of the spider / the scan, instead sending hardcoded "false" or ""  to the API call. 

Regards

**Comment by JordanGS** [comment]
@mabdelmoez Resolved in pull request #41
