### ISSUE TITLE
ascan.scanAsUser method signature comment(s) are misleading 

### ISSUE THREAD

**Issue by mabdelmoez** [jenkinsci/zaproxy-plugin#35]
Hi,

The method signature comments of 	zapClientAPI.ascan.scanAsUser are misleading below is the comment:
// Method signature : scan(String apikey, String url, String recurse, String inscopeonly, String scanpolicyname, String method, String postdata)

However it should be:
// Method signature : scan(String apikey, String url, String contextId, String userId, String recurse, String scanpolicyname, String method, String postdata)

As per to the call:
zapClientAPI.ascan.scanAsUser(API_KEY, url, contextId, userId,"true", chosenPolicy, null, null); 

Also as per to the API code/description snippet featured below:
 if(var1 != null) {
 var9.put("apikey", var1);
  }
  var9.put("url", var2);
  var9.put("contextId", var3);
  var9.put("userId", var4);
  var9.put("recurse", var5);
  var9.put("scanPolicyName", var6);
  var9.put("method", var7);
  var9.put("postData", var8);
   return this.api.callApi("ascan", "action", "scanAsUser", var9);

Regards,

P.S: Also consider //arg2, arg3, arg4, arg5, arg6, arg7)scan(API_KEY, url, "true", "false", chosenPolicy, null, null); to be scan(API_KEY, url, contextId, userId, chosenPolicy, null, null);

**Comment by JordanGS** [comment]
@mabdelmoez use of deprecated api resulted in this bug. Resolved in pull request #41
